# Generated by Django 2.1 on 2019-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('pv_number', models.IntegerField(default=0, verbose_name='点击量')),
            ],
        ),
    ]
